//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyVersion("2.5.0.14")]
[assembly: AssemblyFileVersion("2.5.0.14")]
[assembly: AssemblyCopyright("Copyright (C) Google 2013")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCompany("Google")]
[assembly: AssemblyProduct("Google Checkout .NET Client Wrapper (Release DB: 0)")]


